# Generated by Django 3.2.6 on 2021-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CNC', 'отменен'), ('PRD', 'обрабатывается'), ('STP', 'отправлен в обработку'), ('PD', 'оплачен'), ('RDY', 'готов к выдаче'), ('FM', 'формируется')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
