# Generated by Django 3.2.6 on 2021-11-01 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20211018_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='actication_key',
            new_name='activation_key',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 9, 30, 56, 448770, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
